config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  include Pagy::Backend

 

  # GET /tweets or /tweets.json
 
  def index

   


    
    # Pagy
  

    
    if params[:search]
      @pagy, @tweets = pagy(Tweet.where("description LIKE ?", "%#{params[:search]}%").order(created_at: :desc), items: 9)
    else
      @pagy, @tweets = pagy(Tweet.order(created_at: :desc), items: 9)
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Pajarraco Creado con EXITO!." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Pajarraco Actulizado con EXITO!." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Pajarraco Borrado con EXITO!. " }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :userName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioAppPajarrako</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
 
  </head>

 <body class="bg-body">
     <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="../tweets">PAJARRACO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%= new_tweet_path %>">New Pajarraco</a>
            </li>
          </ul>

          <%= form_tag tweets_path, method: :get, class: "d-flex mb-4", role: "search" do %>
            <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Search", aria_label: "Search" %>
            <%= submit_tag "Search", class: "btn btn-outline-success" %>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="container text-center">
  <%= form_with(model: tweet) do |form| %>
    <% if tweet.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :userName,"Usuario", class: "form-label" %>
          <%= form.text_field :userName, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :description, "Pajarraco", class: "form-label" %>
          <%= form.text_field :description, class: "form-control" %>
        </div>
      </div>
    </div>
<br>
    <div class="form-group">
      <%= form.submit "Nuevo / Editar Pajarraco", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<div class="container text-center">

<div id="<%= dom_id tweet %>">
  
  <h5 class="card-title">  <%= tweet.userName %> </h5>
          <p class="card-text"><%= tweet.description %></p>
</div>

</div>

app/views/tweets/edit.html.erb
<h1 class="text-center">EDITAR MY PAJARRACO</h1>
<div class="container text-center">



<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Regresar al Pajarraco", @tweet %> 
</div>
</div>

app/views/tweets/index.html.erb
<div class="container text-center">
  <p style="color: green"><%= notice %></p>
  <h1>Listado de Pajarracos </h1>
  <div class="row justify-content-center">
    <% @tweets.each do |tweet| %>
      <div class="col-md-4 mb-4">
        <div class="card profile-card-2">
          <div class="card-img-block">
            <%= image_tag("fondo.jpg", class: "img-fluid", alt: "Card image cap") %>
          </div>
          <div class="card-body pt-5">
            <img src="https://randomuser.me/api/portraits/men/64.jpg" alt="profile-image" class="profile"/> 
            <%= render tweet %>
            <div class="icon-block">
              <%= link_to tweet, class: "edit-icon" do %>
                <i class="fa fa-pencil-square">
                  <span class="letter-e">VER</span>
                </i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="row justify-content-center mt-4">
    <div class="col-md-4">
      <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container text-center">

<h1>Nuevo Pajarraco</h1>

<%= render "form", tweet: @tweet %>

<br>



</div>

app/views/tweets/show.html.erb
<h1 class="text-center">VER MY PAJARRACO</h1>

<div class="container text-center">
  <p style="color: green"><%= notice %></p>

  <div class="row justify-content-center">
    <div class="col-md-4 mb-4">
      <div class="card profile-card-2">
        <div class="card-img-block">
          <%= image_tag("fondo.jpg", class: "img-fluid", alt: "Card image cap") %>
        </div>
        <div class="card-body pt-5">
          <img src="https://randomuser.me/api/portraits/men/64.jpg" alt="profile-image" class="profile"/> 
          <%= render @tweet %>
          <div class="icon-block">
            <div class="edit-icon d-inline-block">
              <%= link_to edit_tweet_path(@tweet) do %>
                <i class="fa fa-pencil-square">
                  <span class="letter-e">E</span>
                </i>
              <% end %>
            </div>

            <div class="delete-icon d-inline-block">
              <%= button_to tweet_path(@tweet), method: :delete, data: { confirm: "¿Estás seguro de que deseas eliminar este tweet?" } do %>
                <i class="fa fa-trash">DEL</i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>